# AikoCute bot 

version: 2
updates:
  - package-ecosystem: "csharp-plugins/csharp-plugins/version"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"